@file:Suppress("MagicNumber")

package ru.llm.agent.core.uikit

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color
import androidx.compose.material3.ColorScheme as M3ColorScheme

internal val LocalColorScheme = staticCompositionLocalOf { lightColorScheme() }

internal fun lightColorScheme(): ColorScheme {
    return ColorScheme(
        primary = Color(0xFF6200EE),
        onPrimary = Color.White,
        primaryContainer = Color(0xFFEADDFF),
        onPrimaryContainer = Color(0xFF1D1976),
        inversePrimary = Color(0xFFE0BFFF),
        secondary = Color(0xFF03DAC5),
        onSecondary = Color.White,
        secondaryContainer = Color(0xFFC8FAD6),
        onSecondaryContainer = Color(0xFF00362D),
        tertiary = Color(0xFF7D52FF),
        onTertiary = Color.White,
        tertiaryContainer = Color(0xFFEDE0FF),
        onTertiaryContainer = Color(0xFF240066),
        background = Color(0xFFF8FAFD),
        onBackground = Color(0xFF1C1B1F),
        surface = Color.White,
        onSurface = Color(0xFF1C1B1F),
        surfaceVariant = Color(0xFFE3E3E6),
        onSurfaceVariant = Color(0xFF45454A),
        surfaceTint = Color(0xFF6200EE),
        inverseSurface = Color(0xFF1C1B1F),
        inverseOnSurface = Color(0xFFF4F3F4),
        error = Color(0xFFB3261E),
        onError = Color(0xFFFCEDEC),
        errorContainer = Color(0xFFF9DEDC),
        onErrorContainer = Color(0xFF410002),
        outline = Color(0xFF757378),
        outlineVariant = Color(0xFFCFCED3),
        scrim = Color(0xFF000000),
        surfaceBright = Color(0xFFF0F2F5),
        surfaceDim = Color(0xFFE3E6EB),
        surfaceContainer = Color(0xFFFBFCFF),
        surfaceContainerHigh = Color(0xFFFCFEFF),
        surfaceContainerHighest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFEFF1F5),
        surfaceContainerLowest = Color(0xFFF8FAFD),
        onSurfaceDim = Color(0xFF6E6D71),
        outlineDim = Color(0xFFA9A8AB),
        inverseOutline = Color(0xFF999999),
        inverseOnSurfaceVariant = Color(0xFF999999),
        inverseOnSurfaceDim = Color(0xFF8C8C8C),
        assetNoStatus = Color(0xFFFF5F5F),
        assetNeedsReview = Color(0xFF4DD0E1),
        assetInProgress = Color(0xFF4CD964),
        assetApproved = Color(0xFF4B5065)
    )
}

internal fun darkColorScheme(): ColorScheme {
    return ColorScheme(
        primary = Color(0xFFD5C6FF),
        onPrimary = Color(0xFF3800B4),
        primaryContainer = Color(0xFF4F00BD),
        onPrimaryContainer = Color(0xFFEADDFF),
        inversePrimary = Color(0xFF9D8CFF),
        secondary = Color(0xFF80CBC4),
        onSecondary = Color(0xFF004D48),
        secondaryContainer = Color(0xFF006A62),
        onSecondaryContainer = Color(0xFFA0F4EC),
        tertiary = Color(0xFFD8B7FF),
        onTertiary = Color(0xFF3D00D1),
        tertiaryContainer = Color(0xFF5326D3),
        onTertiaryContainer = Color(0xFFEDE0FF),
        background = Color(0xFF121212),
        onBackground = Color(0xFFE6E6E6),
        surface = Color(0xFF1C1C1E),
        onSurface = Color(0xFFE6E6E6),
        surfaceVariant = Color(0xFF45454A),
        onSurfaceVariant = Color(0xFFCCCCCC),
        surfaceTint = Color(0xFF6200EE),
        inverseSurface = Color(0xFFE6E6E6),
        inverseOnSurface = Color(0xFF1C1C1E),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        outline = Color(0xFF8C8C8C),
        outlineVariant = Color(0xFF45454A),
        scrim = Color(0xFF000000),
        surfaceBright = Color(0xFF2C2C2E),
        surfaceDim = Color(0xFF121212),
        surfaceContainer = Color(0xFF262628),
        surfaceContainerHigh = Color(0xFF2C2C2E),
        surfaceContainerHighest = Color(0xFF363638),
        surfaceContainerLow = Color(0xFF1A1A1C),
        surfaceContainerLowest = Color(0xFF121212),
        onSurfaceDim = Color(0xFF999999),
        outlineDim = Color(0xFF666666),
        inverseOutline = Color(0xFF666666),
        inverseOnSurfaceVariant = Color(0xFF999999),
        inverseOnSurfaceDim = Color(0xFF8C8C8C),
        assetNoStatus = Color(0xFFFF5F5F),
        assetNeedsReview = Color(0xFF4DD0E1),
        assetInProgress = Color(0xFF4CD964),
        assetApproved = Color(0xFF4B5065)
    )
}

@Immutable
data class ColorScheme(
    val primary: Color,
    val onPrimary: Color,
    val primaryContainer: Color,
    val onPrimaryContainer: Color,
    val inversePrimary: Color,
    val secondary: Color,
    val onSecondary: Color,
    val secondaryContainer: Color,
    val onSecondaryContainer: Color,
    val tertiary: Color,
    val onTertiary: Color,
    val tertiaryContainer: Color,
    val onTertiaryContainer: Color,
    val background: Color,
    val onBackground: Color,
    val surface: Color,
    val onSurface: Color,
    val surfaceVariant: Color,
    val onSurfaceVariant: Color,
    val surfaceTint: Color,
    val inverseSurface: Color,
    val inverseOnSurface: Color,
    val error: Color,
    val onError: Color,
    val errorContainer: Color,
    val onErrorContainer: Color,
    val outline: Color,
    val outlineVariant: Color,
    val scrim: Color,
    val surfaceBright: Color,
    val surfaceDim: Color,
    val surfaceContainer: Color,
    val surfaceContainerHigh: Color,
    val surfaceContainerHighest: Color,
    val surfaceContainerLow: Color,
    val surfaceContainerLowest: Color,
    val onSurfaceDim: Color,
    val outlineDim: Color,
    val inverseOutline: Color,
    val inverseOnSurfaceVariant: Color,
    val inverseOnSurfaceDim: Color,
    val assetNoStatus: Color,
    val assetNeedsReview: Color,
    val assetInProgress: Color,
    val assetApproved: Color,
)

internal fun ColorScheme.toM3ColorScheme(): M3ColorScheme {
    return M3ColorScheme(
        primary = primary,
        onPrimary = onPrimary,
        primaryContainer = primaryContainer,
        onPrimaryContainer = onPrimaryContainer,
        inversePrimary = inversePrimary,
        secondary = secondary,
        onSecondary = onSecondary,
        secondaryContainer = secondaryContainer,
        onSecondaryContainer = onSecondaryContainer,
        tertiary = tertiary,
        onTertiary = onTertiary,
        tertiaryContainer = tertiaryContainer,
        onTertiaryContainer = onTertiaryContainer,
        background = background,
        onBackground = onBackground,
        surface = surface,
        onSurface = onSurface,
        surfaceVariant = surfaceVariant,
        onSurfaceVariant = onSurfaceVariant,
        surfaceTint = surfaceTint,
        inverseSurface = inverseSurface,
        inverseOnSurface = inverseOnSurface,
        error = error,
        onError = onError,
        errorContainer = errorContainer,
        onErrorContainer = onErrorContainer,
        outline = outline,
        outlineVariant = outlineVariant,
        scrim = scrim,
        surfaceBright = surfaceBright,
        surfaceDim = surfaceDim,
        surfaceContainer = surfaceContainer,
        surfaceContainerHigh = surfaceContainerHigh,
        surfaceContainerHighest = surfaceContainerHighest,
        surfaceContainerLow = surfaceContainerLow,
        surfaceContainerLowest = surfaceContainerLowest,
    )
}
